version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: gryffen:${GRYFFEN_VERSION:-latest}
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
