"""empty message

Revision ID: cfee667a1d79
Revises: 3b261a4b6684
Create Date: 2023-04-21 00:58:07.145337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfee667a1d79"
down_revision = "3b261a4b6684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("access_token", sa.String(length=60), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "access_token")
    # ### end Alembic commands ###
