"""empty message

Revision ID: e26821b08b9f
Revises: b4a236d3bbd1
Create Date: 2023-04-23 02:13:23.012388

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e26821b08b9f"
down_revision = "b4a236d3bbd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "is_finalized",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "position",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "position",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.add_column(
        "strategy",
        sa.Column("principal_balance", sa.Integer(), nullable=False),
    )
    op.add_column("strategy", sa.Column("max_drawdown", sa.Integer(), nullable=False))
    op.alter_column(
        "strategy",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "strategy",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "strategy",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "public_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "user",
        "access_token",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4",
            collation="utf8mb4_0900_ai_ci",
            length=1024,
        ),
        nullable=False,
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "user",
        "is_superuser",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "user",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "user",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "user",
        "is_superuser",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "user",
        "access_token",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4",
            collation="utf8mb4_0900_ai_ci",
            length=1024,
        ),
        nullable=True,
    )
    op.alter_column(
        "user",
        "public_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "strategy",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "strategy",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "strategy",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.drop_column("strategy", "max_drawdown")
    op.drop_column("strategy", "principal_balance")
    op.alter_column(
        "position",
        "timestamp_updated",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "position",
        "timestamp_created",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "position",
        "is_finalized",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    # ### end Alembic commands ###
