"""empty message

Revision ID: dfeccc07768f
Revises: e26821b08b9f
Create Date: 2023-04-25 00:32:49.391064

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dfeccc07768f"
down_revision = "e26821b08b9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "access_token",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4",
            collation="utf8mb4_0900_ai_ci",
            length=1024,
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "access_token",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4",
            collation="utf8mb4_0900_ai_ci",
            length=1024,
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
