"""empty message

Revision ID: 77bfbeb7abd7
Revises: 14dcf949ce99
Create Date: 2023-04-28 12:43:07.304111

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77bfbeb7abd7"
down_revision = "14dcf949ce99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
