"""empty message

Revision ID: 03fff2c3a61e
Revises: 5e6ba0b9a38e
Create Date: 2023-05-27 15:30:26.833442

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03fff2c3a61e"
down_revision = "5e6ba0b9a38e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
