"""empty message

Revision ID: 241d7bf5cdb6
Revises: d278d9a94020
Create Date: 2023-04-25 00:51:32.536327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "241d7bf5cdb6"
down_revision = "d278d9a94020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategy", sa.Column("grid_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy", "grid_count")
    # ### end Alembic commands ###
