"""empty message

Revision ID: 7459641d8779
Revises: a3667e6f70cc
Create Date: 2023-04-22 16:23:06.558512

"""

# revision identifiers, used by Alembic.
revision = "7459641d8779"
down_revision = "a3667e6f70cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
