"""empty message

Revision ID: d278d9a94020
Revises: dfeccc07768f
Create Date: 2023-04-25 00:47:55.797371

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d278d9a94020"
down_revision = "dfeccc07768f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategy", sa.Column("symbol", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy", "symbol")
    # ### end Alembic commands ###
