"""empty message

Revision ID: 0361737e6f5c
Revises: 0f8b8f598a57
Create Date: 2023-04-28 11:29:09.648789

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0361737e6f5c"
down_revision = "0f8b8f598a57"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activation_code", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activation_id"), "activation", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activation_id"), table_name="activation")
    op.drop_table("activation")
    # ### end Alembic commands ###
