"""empty message

Revision ID: 0f8b8f598a57
Revises: cd8c93496492
Create Date: 2023-04-27 23:44:23.095745

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0f8b8f598a57"
down_revision = "cd8c93496492"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credential", sa.Column("type", sa.String(length=50), nullable=False))
    op.add_column("credential", sa.Column("expires_at", sa.DateTime(), nullable=False))
    op.drop_column("credential", "credential_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credential",
        sa.Column("credential_type", mysql.VARCHAR(length=50), nullable=False),
    )
    op.drop_column("credential", "expires_at")
    op.drop_column("credential", "type")
    # ### end Alembic commands ###
