"""empty message

Revision ID: 5e6ba0b9a38e
Revises: 142e993e7577
Create Date: 2023-05-26 23:35:11.028280

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e6ba0b9a38e"
down_revision = "142e993e7577"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column(
        "user", sa.Column("register_via", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "register_via")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
