"""empty message

Revision ID: d17670eebcaa
Revises: 03fff2c3a61e
Create Date: 2023-05-27 23:23:00.169692

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d17670eebcaa"
down_revision = "03fff2c3a61e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("external_uid", sa.LargeBinary(), nullable=True))
    op.alter_column("user", "password", existing_type=sa.BLOB(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.BLOB(), nullable=True)
    op.drop_column("user", "external_uid")
    # ### end Alembic commands ###
