"""empty message

Revision ID: a3667e6f70cc
Revises: cfee667a1d79
Create Date: 2023-04-21 15:36:08.996765

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a3667e6f70cc"
down_revision = "cfee667a1d79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("public_id", sa.String(length=50), nullable=True))
    op.add_column("user", sa.Column("password", sa.String(length=1024), nullable=False))
    op.create_unique_constraint(None, "user", ["public_id"])
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("hashed_password", mysql.VARCHAR(length=1024), nullable=False),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "password")
    op.drop_column("user", "public_id")
    # ### end Alembic commands ###
