"""empty message

Revision ID: f2cbf5a97fa8
Revises: 7459641d8779
Create Date: 2023-04-22 16:28:12.564239

"""

# revision identifiers, used by Alembic.
revision = "f2cbf5a97fa8"
down_revision = "7459641d8779"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
