"""empty message

Revision ID: e7672c28b751
Revises: 07188504a597
Create Date: 2023-10-04 01:10:36.901702

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e7672c28b751"
down_revision = "07188504a597"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy", "strategy_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy",
        sa.Column(
            "strategy_type", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
