"""empty message

Revision ID: 14dcf949ce99
Revises: 0361737e6f5c
Create Date: 2023-04-28 12:39:54.258836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14dcf949ce99"
down_revision = "0361737e6f5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
