"""empty message

Revision ID: b4a236d3bbd1
Revises: f2cbf5a97fa8
Create Date: 2023-04-22 16:28:47.551506

"""

# revision identifiers, used by Alembic.
revision = "b4a236d3bbd1"
down_revision = "f2cbf5a97fa8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
