"""empty message

Revision ID: 93fd7441c9b2
Revises: 819cbf6e030b
Create Date: 2023-04-27 03:11:56.500516

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93fd7441c9b2"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("entry_price", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("realized_profit", sa.Integer(), nullable=False),
        sa.Column("is_finalized", sa.Boolean(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_id"), "position", ["id"], unique=False)
    op.create_table(
        "strategy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_type", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("upper_bound", sa.Integer(), nullable=False),
        sa.Column("lower_bound", sa.Integer(), nullable=False),
        sa.Column("grid_count", sa.Integer(), nullable=False),
        sa.Column("grid_size", sa.Integer(), nullable=False),
        sa.Column("grid_type", sa.String(length=50), nullable=False),
        sa.Column("principal_balance", sa.Integer(), nullable=False),
        sa.Column("max_drawdown", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategy_id"), "strategy", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strategy_id"), table_name="strategy")
    op.drop_table("strategy")
    op.drop_index(op.f("ix_position_id"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
