name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: griffin-ca510
  SERVICE: gryffen-backend
  REGION: us-central1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'
    - name: Build the Docker image
      run: docker build . --file deploy/Dockerfile --tag "ithomaslin/gryffen:${{ github.sha }}" --platform linux/amd64

    - name: Log in to Docker Hub
      uses: 'docker/login-action@v3'
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image to Docker Hub repo
      run: docker push "ithomaslin/gryffen:${{ github.sha }}"

  deploy:

    needs: build

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@v2'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Google Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ithomaslin/gryffen:${{ github.sha }}
          labels:
            port=8000

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
