name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deploy/Dockerfile --tag ithomaslin/gryffen:$(date +'%Y-%m-%d') --platform linux/amd64

    - name: Push the Docker image to Docker Hub repo
      run: docker push ithomaslin/gryffen:$(date +'%Y-%m-%d')
