name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: griffin-ca510
  SERVICE: gryffen
  REGION: us-central1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'
    - name: Build the Docker image
      run: docker build . --file deploy/Dockerfile --tag "ithomaslin/gryffen:${{ github.sha }}" --platform linux/amd64

    - name: Log in to Docker Hub
      uses: 'docker/login-action@v3'
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image to Docker Hub repo
      run: docker push "ithomaslin/gryffen:${{ github.sha }}"

  deploy:

    needs: build

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@v2'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Google Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ithomaslin/gryffen:${{ github.sha }}
          flags: '--port=8000, --allow-unauthenticated'
          env_vars: |
            GRYFFEN_RELOAD=${{ vars.GRYFFEN_RELOAD }}
            HASH_ITERATION=${{ vars.HASH_ITERATION }}
            NUM_BENCHMARK=${{ vars.NUM_BENCHMARK }}
            UNIX_TIMESTAMP_NEVER_EXPIRE=${{ vars.UNIX_TIMESTAMP_NEVER_EXPIRE }}
            FRONT_END_BASE_URL=${{ vars.FRONT_END_BASE_URL }}
            EMAIL_FROM=${{ vars.EMAIL_FROM }}
            ACCESS_TOKEN_HASH_ALGO=${{ vars.ACCESS_TOKEN_HASH_ALGO }}
            ACCESS_TOKEN_EXPIRE_MINUTES=${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
            OAUTH_TOKEN_EXPIRE_MINUTES=${{ vars.OAUTH_TOKEN_EXPIRE_MINUTES }}
            FINNHUB_WEBSOCKET_URI=${{ vars.FINNHUB_WEBSOCKET_URI }}
            TD_API_AUTH_GATEWAY=${{ vars.TD_API_AUTH_GATEWAY }}
            TD_API_CONSUMER_KEY=${{ secrets.TD_API_CONSUMER_KEY }}
            TD_API_REDIRECT_URL=${{ vars.TD_API_REDIRECT_URL }}
            TD_API_BASE_URL=${{ vars.TD_API_BASE_URL }}
            TD_API_AUTH_URL=${{ vars.TD_API_AUTH_URL }}
            TD_API_ORDERS_URL=${{ vars.TD_API_ORDERS_URL }}
            GRYFFEN_SECRET_KEY=${{ secrets.GRYFFEN_SECRET_KEY }}
            SERVICE_ACCOUNT_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}
            ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY }}
            ALPACA_SECRET_KEY=${{ secrets.ALPACA_SECRET_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
