name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deploy/Dockerfile --tag ithomaslin/gryffen:$(date +'%Y-%m-%d') --platform linux/amd64

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image to Docker Hub repo
      run: |
        docker push ithomaslin/gryffen:$(date +'%Y-%m-%d')
        IMAGE_NAME=ithomaslin/gryffen:$(date +'%Y-%m-%d')
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Exporting variable for next job
      uses: UnlyEd/github-action-store-variable@v3
      with:
        variables: |
          IMAGE_NAME=${{ env.IMAGE_NAME }}

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Import variable IMAGE_NAME
        uses: UnlyEd/github-action-store-variable@v3
        with:
          variables: |
            IMAGE_NAME

      - name: Deploy to Google Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ env.GCP_SERVICE_REGION }}
          image: $IMAGE_NAME

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
